# Generated by Django 2.2.1 on 2019-08-14 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EID', models.CharField(max_length=100)),
                ('CPTID', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('icon', models.ImageField(upload_to='')),
                ('ownuser', models.CharField(max_length=50)),
                ('insert_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 't_dat_instance_info',
            },
        ),
        migrations.CreateModel(
            name='EntityToProp',
            fields=[
                ('CPID', models.BigAutoField(primary_key=True, serialize=False)),
                ('CPTID', models.CharField(max_length=100)),
                ('PROPID', models.CharField(max_length=100)),
                ('insert_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 't_def_concept_property',
            },
        ),
        migrations.CreateModel(
            name='PropDefault',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PROPID', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('sortid', models.IntegerField()),
                ('icon', models.ImageField(upload_to='')),
                ('insert_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 't_def_property_info',
            },
        ),
        migrations.CreateModel(
            name='PropertyData',
            fields=[
                ('EPID', models.BigAutoField(primary_key=True, serialize=False)),
                ('EID', models.CharField(max_length=255)),
                ('PROPID', models.CharField(max_length=255)),
                ('objid', models.DateTimeField()),
                ('prop_value', models.TextField()),
                ('origin', models.CharField(max_length=50)),
                ('ownuser', models.CharField(max_length=50)),
                ('insert_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 't_dat_instance_property_info',
            },
        ),
        migrations.CreateModel(
            name='Relation',
            fields=[
                ('ERID', models.BigAutoField(primary_key=True, serialize=False)),
                ('EID_SUBJECT', models.CharField(max_length=100)),
                ('RID', models.CharField(max_length=255)),
                ('EID_OBJECT', models.CharField(max_length=100)),
                ('reversible', models.BooleanField(default=False)),
                ('ownuser', models.CharField(max_length=100)),
                ('insert_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 't_dat_instance_relation_info',
            },
        ),
    ]
