# Generated by Django 2.2.1 on 2019-08-15 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Concept',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CPID', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('icon', models.ImageField(upload_to='')),
                ('insert_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 't_def_concept_info',
            },
        ),
        migrations.CreateModel(
            name='ConceptHierarchy',
            fields=[
                ('HID', models.BigAutoField(primary_key=True, serialize=False)),
                ('CPTID', models.CharField(max_length=255)),
                ('PID', models.CharField(max_length=255)),
                ('insert_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 't_def_concept_hierarchy',
            },
        ),
        migrations.CreateModel(
            name='PropConceptHierarchy',
            fields=[
                ('HID', models.BigAutoField(primary_key=True, serialize=False)),
                ('PROPID', models.CharField(max_length=255)),
                ('PID', models.CharField(max_length=255)),
                ('insert_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 't_def_property_hierarchy',
            },
        ),
    ]
