# Generated by Django 2.2.1 on 2019-08-19 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_concept_concepthierarchy_propconcepthierarchy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertydata',
            name='objid',
            field=models.CharField(max_length=255),
        ),
    ]
