# Generated by Django 2.2.1 on 2019-08-22 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_adminname_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntityNew',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EID', models.CharField(max_length=100)),
                ('CPTID', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('icon', models.ImageField(upload_to='')),
                ('ownuser', models.CharField(max_length=50, null=True)),
                ('insert_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('check_name', models.CharField(max_length=255, null=True)),
                ('doubt', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 't_dat_instance_info_new',
            },
        ),
        migrations.CreateModel(
            name='PropertyDataNew',
            fields=[
                ('EPID', models.BigAutoField(primary_key=True, serialize=False)),
                ('EID', models.CharField(max_length=255)),
                ('PROPID', models.CharField(max_length=255)),
                ('objid', models.CharField(max_length=255, null=True)),
                ('prop_value', models.TextField()),
                ('origin', models.CharField(max_length=50, null=True)),
                ('ownuser', models.CharField(max_length=50, null=True)),
                ('insert_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('doubt', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 't_dat_instance_property_info_new',
            },
        ),
        migrations.AddField(
            model_name='entity',
            name='check_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
