# Generated by Django 2.2.1 on 2019-08-22 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20190822_1911'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='check',
            field=models.BooleanField(default=False),
        ),
    ]
